apiVersion: v1
kind: Service
metadata:
  name: hotstar-service  # Name of your service
spec:
  selector:
    app: hotstar-app  # Targets pods with the matching label
  ports:
  - port: 3000  # External port exposed by the service
    targetPort: 3000  # Port on the pods to forward traffic to
  type: LoadBalancer  # Exposes the service on each node's IP at a high port
